
language: node_js

node_js:
  - "8.11.1"

before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis CI" && git remote add ci https://$GH_TOKEN@github.com/seiyria/gameicons-font.git
deploy:
  - edge: true
    skip_cleanup: true
    provider: script
    script: npm run fulldeploy:ci
    on:
      branch: master